@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTcxNjFhZThmYTc3OWE2ZjQ5ZDY1YjQiLCJpYXQiOjE3NjkzOTExODAsImV4cCI6MTc2OTM5NDc4MH0.pD1a-ViOKA67bud_-QTgzb8vz6RIRBO_hV6qXTjMa6I
### Login user
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin.role@example.com",
  "password": "password123"
}

### Register new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Mariano Martinez",
  "username": "mariano.martinez",
  "email": "mariano.martinez@example.com",
  "password": "password123"
}

### Logout user
POST http://localhost:8080/api/v1/auth/logout
Cookie: access_token={{authToken}}
