@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTcxNjFhZThmYTc3OWE2ZjQ5ZDY1YjQiLCJpYXQiOjE3NjkzOTExODAsImV4cCI6MTc2OTM5NDc4MH0.pD1a-ViOKA67bud_-QTgzb8vz6RIRBO_hV6qXTjMa6I

### Create a new user
POST http://localhost:8080/api/v1/users/
Cookie: access_token={{authToken}}
Content-Type: application/json

{
  "name": "Mariano Martinez",
  "username": "mariano.martinez",
  "email": "mariano.martinez@example.com",
  "password": "password123"
}

### Get all user 
GET http://localhost:8080/api/v1/users
Cookie: access_token={{authToken}}

### Get user by ID
GET http://localhost:8080/api/v1/users/6976ba84445f11b4a93dbd0e
Cookie: access_token={{authToken}}
### Update user by ID
PATCH  http://localhost:8080/api/v1/users/6976ba84445f11b4a93dbd0e
Cookie: access_token={{authToken}}
Content-Type: application/json  

{

}

### Delete user by ID
DELETE   http://localhost:8080/api/v1/users/6976b6eaeca0d1a9e479b5d0
Cookie: access_token={{authToken}}