import { z } from "zod";

// Schema for creating a new user - id is auto-generated by MongoDB
export const UserSchema = z.object({
  name: z
    .string()
    .trim()
    .min(5, "Name must be at least 5 characters long")
    .max(100),
  username: z
    .string()
    .trim()
    .min(5, "Username must be at least 5 characters long")
    .max(50),
  email: z.string().email("Invalid email address").max(100),
});

// For updating user - all fields optional
export const UpdateUserSchema = z.object({
  name: z
    .string()
    .trim()
    .min(5, "Name must be at least 5 characters long")
    .max(100)
    .optional(),
  username: z
    .string()
    .trim()
    .min(5, "Username must be at least 5 characters long")
    .max(50)
    .optional(),
  email: z.string().email("Invalid email address").max(100).optional(),
});
